[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format = true
formatter = { command = "shfmt" }
grammar = "bash"

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true
formatter = { command = "taplo" }
grammar = "toml"
roots = ["."]

[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = true
formatter = { command = "dprint", args = ["fmt", "-", "--stdin"] }
